# Generated by Django 6.0.6 on 2026-06-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.CharField(choices=[(1, '1 Year'), (2, '2 Year'), (3, '3 Year'), (4, '4 Year'), (5, '5 Year')])),
                ('prices', models.PositiveIntegerField()),
                ('discount', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
