# Generated by Django 6.0.6 on 2026-06-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='discount',
            field=models.PositiveIntegerField(),
        ),
    ]
