# Generated by Django 6.0.6 on 2026-06-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='duration',
        ),
    ]
