# Generated by Django 6.0.6 on 2026-06-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_courses_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
