# Generated by Django 6.0.6 on 2026-06-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courses_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(choices=[(1, '1 Year'), (2, '2 Year'), (3, '3 Year'), (4, '4 Year'), (5, '5 Year')]),
        ),
    ]
