# Generated by Django 6.0.6 on 2026-06-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courses_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='levels',
            field=models.CharField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1),
        ),
    ]
