# Generated by Django 6.0.6 on 2026-06-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courses_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='levels',
        ),
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.IntegerField(choices=[(1, 'No Category'), (2, 'Web Development'), (3, 'Data Science & AI'), (4, 'UI/UX Design')], default=1),
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1),
        ),
        migrations.AlterField(
            model_name='courses',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(choices=[(1, '1 Year'), (2, '2 Year'), (3, '3 Year'), (4, '4 Year'), (5, '5 Year')], default=1),
        ),
        migrations.AlterField(
            model_name='courses',
            name='prices',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
