# Generated by Django 6.0.6 on 2026-06-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_courses_levels_courses_category_courses_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='prices',
            new_name='price',
        ),
    ]
