# Generated by Django 6.0.6 on 2026-06-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_prices_courses_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(choices=[(1, '3 Months'), (2, '6 Months'), (3, '9 Months'), (4, '1 Year'), (5, '2 Year'), (6, '3 Year'), (7, '4 Year'), (8, '5 Year')], default=4),
        ),
    ]
