# Generated by Django 6.0.6 on 2026-06-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_courses_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='thumbnail',
            field=models.ImageField(blank=True, default='courses/thumbnail/default.jpg', null=True, upload_to='courses/thumbnail'),
        ),
    ]
