# Generated by Django 6.0.6 on 2026-06-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_courses_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.IntegerField(choices=[(1, 'No Category'), (2, 'Web Development'), (3, 'Data Science & AI'), (4, 'UI/UX Design'), (5, 'Cloud Engineering & DevOps')], default=1),
        ),
    ]
