# Generated by Django 6.0.6 on 2026-06-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_courses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.IntegerField(choices=[(1, 'Web Development'), (2, 'Data Science & AI'), (3, 'UI/UX Design'), (4, 'Cloud Engineering & DevOps')]),
        ),
    ]
