# Generated by Django 6.0.6 on 2026-06-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_courses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.CharField(choices=[('No Category', 'No Category'), ('Web Development', 'Web Development'), ('Data Science & AI', 'Data Science & AI'), ('UI/UX Design', 'UI/UX Design'), ('Cloud Engineering & DevOps', 'Cloud Engineering & DevOps')], max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(choices=[('3 Months', '3 Months'), ('6 Months', '6 Months'), ('9 Months', '9 Months'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5 Years', '5 Years')], default='1 Year', max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50),
        ),
    ]
