# Generated by Django 6.0.6 on 2026-06-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_courses_category_alter_courses_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Data Science & AI', 'Data Science & AI'), ('UI/UX Design', 'UI/UX Design'), ('Cloud Engineering & DevOps', 'Cloud Engineering & DevOps')], max_length=50),
        ),
    ]
