# Generated by Django 6.0.6 on 2026-06-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_courses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.IntegerField(choices=[(1, 'Web Development'), (2, 'Data Science & AI'), (3, 'UI/UX Design'), (4, 'Cloud Engineering & DevOps')]),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(choices=[(1, '3 Months'), (2, '6 Months'), (3, '9 Months'), (4, '1 Year'), (5, '2 Year'), (6, '3 Year'), (7, '4 Year'), (8, '5 Year')], default=4),
        ),
        migrations.AlterField(
            model_name='courses',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1),
        ),
    ]
